// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkIRfe_UplX_ben-c4WMQqn4rY7IiVghE',
    appId: '1:722775736268:web:b3c9283aa0c007672ce769',
    messagingSenderId: '722775736268',
    projectId: 'flutterfirebase-9159a',
    authDomain: 'flutterfirebase-9159a.firebaseapp.com',
    storageBucket: 'flutterfirebase-9159a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2H-DZ0jYW5zhakBRO3xhQMEpRyC9KEfE',
    appId: '1:722775736268:android:5de61bd94fd057b62ce769',
    messagingSenderId: '722775736268',
    projectId: 'flutterfirebase-9159a',
    storageBucket: 'flutterfirebase-9159a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAzdUJYJlm_ET3wfKQQtEWuMle-pTX6hs',
    appId: '1:722775736268:ios:d492671f4b376b7e2ce769',
    messagingSenderId: '722775736268',
    projectId: 'flutterfirebase-9159a',
    storageBucket: 'flutterfirebase-9159a.firebasestorage.app',
    iosBundleId: 'com.example.waveAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAzdUJYJlm_ET3wfKQQtEWuMle-pTX6hs',
    appId: '1:722775736268:ios:d492671f4b376b7e2ce769',
    messagingSenderId: '722775736268',
    projectId: 'flutterfirebase-9159a',
    storageBucket: 'flutterfirebase-9159a.firebasestorage.app',
    iosBundleId: 'com.example.waveAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkIRfe_UplX_ben-c4WMQqn4rY7IiVghE',
    appId: '1:722775736268:web:444d47e02c51ba902ce769',
    messagingSenderId: '722775736268',
    projectId: 'flutterfirebase-9159a',
    authDomain: 'flutterfirebase-9159a.firebaseapp.com',
    storageBucket: 'flutterfirebase-9159a.firebasestorage.app',
  );
}
